name: nagada_client_sdk
description: "Nagada client SDK for Dart (production-ready example)"
version: 0.1.0
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.17.0

dev_dependencies:
  test: ^1.21.0
